### PR TITLE
Payment module DONE for 2.0 beta front! 

### PR DESCRIPTION
**Pull request by troldmand**
Bugs: 
- Still a small scaling issue with the QR-code. Needs to be fixed when final bitcoin set-up is implemented. 
- Bitcoin footer is not there yet. 
- Small nudging needs to be done 
- Oh! Almost forgot! The code is def. NOT clean! Will commit a new one later tonight. 

But yeah.

### CODE REVIEW

**Comment by troldmand** [comment]
Woooow! Why are they all unverified?!

**Comment by dotnetCarpenter** [comment]
@troldmand That is because you are signing with the wrong PGP key. You need to sign with the key you have in github or add your default signing key to github. We had the same problem when you tried to sign my public pgp key. You where signing with another key than the one you use to use for signing commits.

**Comment by troldmand** [comment]
@dotnetCarpenter OK, I updated my configs, and followed your guidance, Grand Maester Jon. And it worked! It was a bit of a battle, and I also ran git rebase --continue twice I think, but it seems to be the right strategy combined with the 'never pull' / force push strategy. Now I'm just wondering, if this is sufficient? I'm afraid that it's not, and I need to do it with all the above unverified commits too?

**Comment by troldmand** [comment]
I did it! It asked me to squash the unverified commits. And I did. Hopefully this is sufficient?

**Comment by dotnetCarpenter** [comment]
Unfortunately, you either merged via github.com or you forgot to sign your
merge commit.

https://github.com/Firefund/frontend/commits/master

We got a few unsigned commits and one of your commits
(1e8b6da49e6f94bb3d22afa9dcb9c80346025eea) is signed with the wrong key.

I will be off-line for little while but so far it is only the last 4
commits which are unsigned. I think we can manage to `rebase -i` that and
sign the commits. Its better if you and @magiker420 do it with your keys or
I will be the owner of the commits, making it difficult to trace who made
what.

**Pull request merged**
